stages:
  split:
    cmd: python ./src/data/split_data.py
    deps:
    - data/raw
    - src/data/split_data.py
    outs:
    - data/processed
  normalize:
    cmd: python src/data/normalize_data.py
    deps:
    - data/processed
    - src/data/normalize_data.py
