stages:
  split:
    cmd: python ./src/data/split_data.py
    deps:
    - data/raw/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
  normalize:
    cmd: python src/data/normalize_data.py
    deps:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - src/data/normalize_data.py
    outs:
    - data/processed/X_train_scaled.csv
    - data/processed/X_test_scaled.csv
