split_data:
  test_size: 0.2
  random_state: 246
grid_search:
  model: RandomForestRegressor
  random_state: 246
  cv: 3
  scoring: neg_mean_squared_error
  n_jobs: -1
  param_grid:
    n_estimators:
      - 100
      - 200
      - 300
    max_depth:
      - null
      - 5
      - 10
    min_samples_split:
      - 2
      - 5
      - 10
    min_samples_leaf:
      - 1
      - 2
      - 4
